package com.example.springboot.hellospringboot.domain.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orderdetails
 */
public class OrderdetailsKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.orderNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private Integer ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.productCode
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.orderNumber
     *
     * @return the value of orderdetails.orderNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public OrderdetailsKey withOrdernumber(Integer ordernumber) {
        this.setOrdernumber(ordernumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.orderNumber
     *
     * @param ordernumber the value for orderdetails.orderNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.productCode
     *
     * @return the value of orderdetails.productCode
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public OrderdetailsKey withProductcode(String productcode) {
        this.setProductcode(productcode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.productCode
     *
     * @param productcode the value for orderdetails.productCode
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ordernumber=").append(ordernumber);
        sb.append(", productcode=").append(productcode);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderdetailsKey other = (OrderdetailsKey) that;
        return (this.getOrdernumber() == null ? other.getOrdernumber() == null : this.getOrdernumber().equals(other.getOrdernumber()))
            && (this.getProductcode() == null ? other.getProductcode() == null : this.getProductcode().equals(other.getProductcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrdernumber() == null) ? 0 : getOrdernumber().hashCode());
        result = prime * result + ((getProductcode() == null) ? 0 : getProductcode().hashCode());
        return result;
    }
}