package com.example.springboot.hellospringboot.domain.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orderdetails
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class Orderdetails extends OrderdetailsKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.quantityOrdered
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private Integer quantityordered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.priceEach
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private BigDecimal priceeach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.orderLineNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private Short orderlinenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.quantityOrdered
     *
     * @return the value of orderdetails.quantityOrdered
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Integer getQuantityordered() {
        return quantityordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Orderdetails withQuantityordered(Integer quantityordered) {
        this.setQuantityordered(quantityordered);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.quantityOrdered
     *
     * @param quantityordered the value for orderdetails.quantityOrdered
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public void setQuantityordered(Integer quantityordered) {
        this.quantityordered = quantityordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.priceEach
     *
     * @return the value of orderdetails.priceEach
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public BigDecimal getPriceeach() {
        return priceeach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Orderdetails withPriceeach(BigDecimal priceeach) {
        this.setPriceeach(priceeach);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.priceEach
     *
     * @param priceeach the value for orderdetails.priceEach
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public void setPriceeach(BigDecimal priceeach) {
        this.priceeach = priceeach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.orderLineNumber
     *
     * @return the value of orderdetails.orderLineNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Short getOrderlinenumber() {
        return orderlinenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public Orderdetails withOrderlinenumber(Short orderlinenumber) {
        this.setOrderlinenumber(orderlinenumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.orderLineNumber
     *
     * @param orderlinenumber the value for orderdetails.orderLineNumber
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    public void setOrderlinenumber(Short orderlinenumber) {
        this.orderlinenumber = orderlinenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", quantityordered=").append(quantityordered);
        sb.append(", priceeach=").append(priceeach);
        sb.append(", orderlinenumber=").append(orderlinenumber);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orderdetails other = (Orderdetails) that;
        return (this.getOrdernumber() == null ? other.getOrdernumber() == null : this.getOrdernumber().equals(other.getOrdernumber()))
            && (this.getProductcode() == null ? other.getProductcode() == null : this.getProductcode().equals(other.getProductcode()))
            && (this.getQuantityordered() == null ? other.getQuantityordered() == null : this.getQuantityordered().equals(other.getQuantityordered()))
            && (this.getPriceeach() == null ? other.getPriceeach() == null : this.getPriceeach().equals(other.getPriceeach()))
            && (this.getOrderlinenumber() == null ? other.getOrderlinenumber() == null : this.getOrderlinenumber().equals(other.getOrderlinenumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrdernumber() == null) ? 0 : getOrdernumber().hashCode());
        result = prime * result + ((getProductcode() == null) ? 0 : getProductcode().hashCode());
        result = prime * result + ((getQuantityordered() == null) ? 0 : getQuantityordered().hashCode());
        result = prime * result + ((getPriceeach() == null) ? 0 : getPriceeach().hashCode());
        result = prime * result + ((getOrderlinenumber() == null) ? 0 : getOrderlinenumber().hashCode());
        return result;
    }
}