package com.example.springboot.hellospringboot.dao.mbg;

import com.example.springboot.hellospringboot.domain.pojo.Orderdetails;
import com.example.springboot.hellospringboot.domain.pojo.OrderdetailsKey;
import com.example.springboot.hellospringboot.domain.query.example.OrderdetailsExample;
import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    long countByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int deleteByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int deleteByPrimaryKey(OrderdetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    List<Orderdetails> selectByExample(OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    Orderdetails selectByPrimaryKey(OrderdetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") Orderdetails record, @Param("example") OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int updateByExample(@Param("record") Orderdetails record, @Param("example") OrderdetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int updateByPrimaryKey(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Fri Jan 14 15:52:36 CST 2022
     */
    int insertBatch(Collection<Orderdetails> records);
}