
server:
  port: 80


management:
  endpoints:
    web:
      exposure:
        include: beans,trace # 可以通过http://localhost/actuator/beans查看bean
spring:
  jdbc:
    datasource:
      druid:
        yiibai:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/yiibaidb
          username: root
          password: root
  datasource:
    redis:
      host: 127.0.0.1
      port: 6379
      password: admin

hello-world: Hello World!