
server:
  port: 80


management:
  endpoints:
    web:
      exposure:
        include: beans,trace # 可以通过http://localhost/actuator/beans查看bean
spring:
  jdbc:
    datasource:
      druid:
        yiibai:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/yiibaidb
          username: root
          password: admin
        yiibaidb-properties:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dmp
          username: root
          password: admin
  datasource:
    redis:
      host: localhost
      port: 63790
      password: admin

hello-world: Hello World!